name: Linux Tests

on:
  push:
    branches:
      - meson
      - for_run
  pull_request:
    branches:
      - meson
      - for_run

jobs:
  test_meson:
    name: Meson build
    if: "github.repository == 'Smit-create/scipy' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]') && !contains(github.ref, 'maintenance/') && !contains(github.base_ref, 'maintenance/')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Ubuntu dependencies
      run: |
        # NOTE: not the same OpenBLAS version as in upstream CI (I'm being lazy here)
        sudo apt-get install libopenblas-dev libatlas-base-dev liblapack-dev gfortran libgmp-dev libmpfr-dev libsuitesparse-dev ccache libmpc-dev
    - name: Install Python packages
      run: |
        python -m pip install numpy setuptools wheel cython pytest pytest-xdist pybind11 pytest-xdist mpmath gmpy2 pythran ninja asv virtualenv
        python -m pip install --user git+https://github.com/rgommers/meson.git@fix-cython-mixed-sources
    - name: Build SciPy
      run: |
        meson setup build --prefix=$PWD/installdir
        ninja -C build -j 2
    - name: Install SciPy
      run: |
        meson install -C build
    - name: Benchmark SciPy
      run: |
        export PYTHONPATH=$PWD/installdir/lib/python3.9/site-packages/
        pushd benchmarks
        asv machine --yes --config asv.conf.json
        popd
        python runtests.py -n --bench | tee benchmark_result.txt
    
    - name: Upload results as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: benchmarks
        path: |
          benchmark_result.txt
